# -*- coding: utf-8 -*-
"""onlineinterntask2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IwhFd2Yk-fxqVnCU_P_t41cOjADJs0Q
"""

# PREDICTIVE MODELING USING MACHINE LEARNING

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# ----------------------------------------
# LOAD DATASET
# ----------------------------------------

iris = load_iris()

# Create dataframe
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Target column
df['flower'] = iris.target

print(df.head())

# ----------------------------------------
# SPLIT DATA
# ----------------------------------------

X = df.drop('flower', axis=1)
y = df['flower']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# ----------------------------------------
# TRAIN MODEL
# ----------------------------------------

model = RandomForestClassifier()

model.fit(X_train, y_train)

# ----------------------------------------
# PREDICTION
# ----------------------------------------

y_pred = model.predict(X_test)

# ----------------------------------------
# MODEL ACCURACY
# ----------------------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nModel Accuracy:", accuracy)

# ----------------------------------------
# CONFUSION MATRIX
# ----------------------------------------

cm = confusion_matrix(y_test, y_pred)

display = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=iris.target_names
)

display.plot()

plt.title("Confusion Matrix")
plt.show()

print("\nProject Completed Successfully!")