# -*- coding: utf-8 -*-
"""onlineinterntask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tjo4wUFolGYkg3JXASL2DbFHyqItQAxx
"""

# DATA CLEANING & VISUALIZATION PROJECT USING IRIS DATASET

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

#Load iris dataset
iris = load_iris()

# Create dataframe
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Add flower names
df['flower'] = [iris.target_names[i] for i in iris.target]

# Display first 5 rows
print("First 5 Rows:")
print(df.head())

# -----------------------------------
# DATA CLEANING
# -----------------------------------

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicate rows
df = df.drop_duplicates()

print("\nDuplicates Removed Successfully")

#----------------------------------
# DATA VISUALIZATION
# -----------------------------------

# Histogram
df.hist(figsize=(10,8))
plt.show()
# Scatter Plot
plt.figure(figsize=(6,4))

plt.scatter(df['sepal length (cm)'],
            df['petal length (cm)'])

plt.title("Sepal Length vs Petal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")

plt.show()

#-----------------------------------
# SAVE CLEANED DATA
# -----------------------------------

df.to_csv("cleaned_iris_dataset.csv", index=False)

print("\nProject Completed Successfully!")